import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Nav from '@/components/Nav'
import Provider from '@/components/Provider'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Medicare',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Provider>
          <main className='flex-grow'>
            <Nav className="z-1" />
            {children}
            {/* <Footer /> */}
          </main>
        </Provider>
      </body>
    </html>
  )
}
